nn:
        scrape_yahoo_finance: yes
        loss: mse
        epochs: 400
        validation_split: 0.00
        learning_rate: 0.0025
        pre_process: min_max
        train_test_split: 0.90
        look_ahead_days: 1
        suppliers:
                - JBL
                - MU
                - QCOM
                - DIOD
                - STM
                - TXN
                - ADI
                - GLUU
        features:
                - bollinger_bands
                - money_flow_index
                - average_directional_movement_index
                - momentum
                - hodrick_prescott
                - trix
                - relative_strength_index
                - moving_average:
                        window_1: 10
                        window_2: 5
                        window_4: 40
                - rolling_standard_deviation:
                        window_1: 7
                - absolute_price_oscillator
        metric:
                - mean_squared_error
                - mean_absolute_error
        optimizer: Adam
        layers:
                - layer_1:
                        type: feedforward
                        activation: relu
                        dropout: 0.00
                        nuerons: 30
                - layer_3:
                        type: feedforward
                        activation: relu
                        dropout: 0.20
                        nuerons: 30
                - layer_4:
                        type: feedforward
                        activation: relu
                        dropout: 0.00
                        nuerons: 30
                - layer_5:
                        type: feedforward
                        activation: linear
                        dropout: 0.00
                        nuerons: 1

