nn:
        scrape_yahoo_finance: no
        loss: mse
        epochs: 400
        validation_split: 0.00
        learning_rate: 0.0050
        pre_process: z_score
        transformation: log
        train_test_split: 0.90
        look_ahead_days: 1
        suppliers:
                - JBL
                - MU
                - QCOM
                - DIOD
                - STM
                - TXN
                - ADI
                - GLUU
                - MMM
                - VSH
                - QRVO
                - APH
                - AVGO
                - GLW
                - INTC
                - MXIM
                - ON
                - RRD
                - BRK-A
                - BRK-B
                - SWKS
                - CC
        features:
                - bollinger_bands
                - money_flow_index
                - average_directional_movement_index
                - momentum
                - hodrick_prescott
                - trix
                - relative_strength_index
                - moving_average:
                        window_1: 7
                        window_2: 14
                        window_4: 21
                - rolling_standard_deviation:
                        window_1: 7
                - absolute_price_oscillator
        metric:
                - mean_squared_error
                - mean_absolute_error
        optimizer: Adam
        layers:
                - layer_1:
                        type: feedforward
                        activation: relu
                        dropout: 0.00
                        nuerons: 35
                        kernel_regularizer: 0.000000
                - layer_3:
                        type: feedforward
                        activation: relu
                        dropout: 0.00
                        nuerons: 35
                        kernel_regularizer: 0.0000000
                - layer_4:
                        type: feedforward
                        activation: relu
                        dropout: 0.00
                        nuerons: 35
                        kernel_regularizer: 0.0000000
                - layer_2:
                        type: feedforward
                        activation: relu
                        dropout: 0.00
                        nuerons: 35
                        kernel_regularizer: 0.000000
                - layer_5:
                        type: feedforward
                        activation: linear
                        dropout: 0.00
                        nuerons: 1
                        kernel_regularizer: 0


